name: 'Mirror Branch'
description: 'Mirror a source branch to a destination branch within the same repository'
inputs:
  github-token:
    description: 'This should be `secrets.GITHUB_TOKEN`.'
    required: true
  source:
    description: 'Name of the source branch'
    required: true
  dest:
    description: 'Name of the destination branch'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
